### ISSUE TITLE
Soundtrack downloads everytime, regardless of whether it has already been downloaded.

### ISSUE THREAD

**Issue by johnlage** [Nanolx/patchimage#1]
If you already have the Soundtrack in the directory, the script shouldn't redownload the soundtrack, right?

**Comment by Nanolx** [comment]
Do you have PATCHIMAGE_SOUNDTRACK_DOWNLOAD=TRUE in ~/.patchimage.rc? If so, set it to FALSE and the issue should be solved, if not I'd need more info (game you wanna build, distribution, patchimage version).

**Comment by Nanolx** [comment]
I found the issue, will be fixed in the upcoming 7.0.0 (is already in git version)
